### ISSUE TITLE
jmeter --addprop property file not found when invoking over  ant jmeter task

### ISSUE THREAD

**Issue by cboris** [jfifield/ant-jmeter#1]
It reports file is not found when using jmeterarg nested property. Jmeter is 2.5, jmeter-ant 1.1.1

<jmeter jmeterhome="${jmeterhome}" 

```
                testplan="work/crawlAuthorPages/author-tree-navigation-with-datafile.jmx" 

                resultlog="results/crawlAuthorPages/crawlAuthorPages.jtl"
                jmeterlogfile="results/crawlAuthorPages/jmeter.log"
                failureProperty="crawlAuthorPages.failed">
                <!-- adding additional property file-->
                <jmeterarg value="-q ${jmeter-addprops}"/>
                <property name="jmeter.save.saveservice.assertion_results" value="all"/>


            </jmeter>
```

2013/08/26 13:26:46 WARN  - jmeter.JMeter: Can't find additional property file:  /Users/bpetrovic/Documents/netcentric/testing/src-netcentric/perftest-ubsfit/ubsfit/toughday-netcentric/toughday/work/crawlAuthorPages/addprop.properties java.io.FileNotFoundException:  /Users/bpetrovic/Documents/netcentric/testing/src-netcentric/perftest-ubsfit/ubsfit/toughday-netcentric/toughday/work/crawlAuthorPages/addprop.properties (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.apache.jmeter.JMeter.initializeProperties(JMeter.java:595)
        at org.apache.jmeter.JMeter.start(JMeter.java:286)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.apache.jmeter.NewDriver.main(NewDriver.java:209)

**Comment by eostermueller** [comment]
I had this problem also and I triple-checked my file location to the error message, and I couldn't get it working.  In JMeterTask.java, I found support for an undocumented property named additionalUserProperties (the JMeter -q).

So I compiled and jar'd up the source and the new property worked just fine.
Could you make a new release that includes support for this additionalUserProperties?
I'd be happy to test it for you.
Thanks,
--Erik
